### ISSUE TITLE
Failing to import esutil

### ISSUE THREAD

**Issue by n1md4** [esheldon/esutil#53]
```
debian:~/code/git/esutil$ python3 setup.py install --home=/opt/local/esutil/0.6.5/
running install
running build
running build_py
running build_ext
running install_lib
creating /opt/local/esutil/0.6.5/lib
creating /opt/local/esutil/0.6.5/lib/python
creating /opt/local/esutil/0.6.5/lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/oracle_util.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/sqlite_util.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/random.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/hist_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/int_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/sfile_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/pickle_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/unit_tests/htm_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests
copying build/lib.linux-x86_64-3.5/esutil/sfile.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/recfile/Util.py -> /opt/local/esutil/0.6.5//lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/recfile/test.py -> /opt/local/esutil/0.6.5//lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/recfile/_records.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/recfile/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/recfile/records.py -> /opt/local/esutil/0.6.5//lib/python/esutil/recfile
copying build/lib.linux-x86_64-3.5/esutil/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/stat/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/stat/unit_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/stat/_stat_util.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/stat/util.py -> /opt/local/esutil/0.6.5//lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/stat/_chist.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/stat
copying build/lib.linux-x86_64-3.5/esutil/ostools.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/cosmology
copying build/lib.linux-x86_64-3.5/esutil/cosmology/cosmology.py -> /opt/local/esutil/0.6.5//lib/python/esutil/cosmology
copying build/lib.linux-x86_64-3.5/esutil/cosmology/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/cosmology
copying build/lib.linux-x86_64-3.5/esutil/cosmology/_cosmolib.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/cosmology
copying build/lib.linux-x86_64-3.5/esutil/hdfs.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/fits.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/coords.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/pbar.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/misc.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/algorithm.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/xmltools.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/wcsutil.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/integrate
copying build/lib.linux-x86_64-3.5/esutil/integrate/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/integrate
copying build/lib.linux-x86_64-3.5/esutil/integrate/_cgauleg.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/integrate
copying build/lib.linux-x86_64-3.5/esutil/integrate/util.py -> /opt/local/esutil/0.6.5//lib/python/esutil/integrate
copying build/lib.linux-x86_64-3.5/esutil/cosmology_purepy.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/numpy_util.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/stomp_util.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/plotting.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/json_util.py -> /opt/local/esutil/0.6.5//lib/python/esutil
copying build/lib.linux-x86_64-3.5/esutil/io.py -> /opt/local/esutil/0.6.5//lib/python/esutil
creating /opt/local/esutil/0.6.5/lib/python/esutil/htm
copying build/lib.linux-x86_64-3.5/esutil/htm/__init__.py -> /opt/local/esutil/0.6.5//lib/python/esutil/htm
copying build/lib.linux-x86_64-3.5/esutil/htm/unit_tests.py -> /opt/local/esutil/0.6.5//lib/python/esutil/htm
copying build/lib.linux-x86_64-3.5/esutil/htm/_htmc.cpython-35m-x86_64-linux-gnu.so -> /opt/local/esutil/0.6.5//lib/python/esutil/htm
copying build/lib.linux-x86_64-3.5/esutil/htm/htm.py -> /opt/local/esutil/0.6.5//lib/python/esutil/htm
copying build/lib.linux-x86_64-3.5/esutil/htm/htmc.py -> /opt/local/esutil/0.6.5//lib/python/esutil/htm
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/oracle_util.py to oracle_util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/sqlite_util.py to sqlite_util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/random.py to random.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/hist_tests.py to hist_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/int_tests.py to int_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/sfile_tests.py to sfile_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/pickle_tests.py to pickle_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/unit_tests/htm_tests.py to htm_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/sfile.py to sfile.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/recfile/Util.py to Util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/recfile/test.py to test.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/recfile/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/recfile/records.py to records.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/stat/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/stat/unit_tests.py to unit_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/stat/util.py to util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/ostools.py to ostools.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/cosmology/cosmology.py to cosmology.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/cosmology/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/hdfs.py to hdfs.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/fits.py to fits.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/coords.py to coords.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/pbar.py to pbar.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/misc.py to misc.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/algorithm.py to algorithm.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/xmltools.py to xmltools.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/wcsutil.py to wcsutil.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/integrate/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/integrate/util.py to util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/cosmology_purepy.py to cosmology_purepy.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/numpy_util.py to numpy_util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/stomp_util.py to stomp_util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/plotting.py to plotting.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/json_util.py to json_util.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/io.py to io.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/htm/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/htm/unit_tests.py to unit_tests.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/htm/htm.py to htm.cpython-35.pyc
byte-compiling /opt/local/esutil/0.6.5//lib/python/esutil/htm/htmc.py to htmc.cpython-35.pyc
running install_egg_info
Writing /opt/local/esutil/0.6.5//lib/python/esutil-0.6.5.egg-info
```
```
debian:~/code/git/esutil$ python3
Python 3.5.3 (default, Nov 18 2020, 21:09:16) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import esutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/npkd46/code/git/esutil/esutil/__init__.py", line 113, in <module>
    from . import integrate
  File "/home/npkd46/code/git/esutil/esutil/integrate/__init__.py", line 1, in <module>
    from . import util
  File "/home/npkd46/code/git/esutil/esutil/integrate/util.py", line 20, in <module>
    from .. import stat
  File "/home/npkd46/code/git/esutil/esutil/stat/__init__.py", line 27, in <module>
    from . import util
  File "/home/npkd46/code/git/esutil/esutil/stat/util.py", line 69, in <module>
    from . import _stat_util
ImportError: cannot import name '_stat_util'
>>> 
```

Any ideas?

**Comment by esheldon** [comment]
It looks like you are importing it from the directory where the git checkout is.  python is getting confused and trying to import the local directory.

can you try changing to another directory and then running python?

**Comment by n1md4** [comment]
Thanks.  Some progress.

```
debian:~$ env|grep esutil
PYTHONPATH=:/opt/local/esutil/0.6.5/
debian:~$ python3
Python 3.5.3 (default, Nov 18 2020, 21:09:16) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import esutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'esutil'
```

**Comment by esheldon** [comment]
looks like you need additional parts to your python path. From the install it seems it should be `/opt/local/esutil/0.6.5/lib/python/`
```
# bash
export PYTHONPATH=$PYTHONPATH:/opt/local/esutil/0.6.5/lib/python/
# chs/tcsh
setenv PYTHONPATH $PYTHONPATH:/opt/local/esutil/0.6.5/lib/python/
```

By the way, you can also use `pip install esutil` (or `conda install esutil` if you have conda forge in your channels) and then you don't have to install from source

**Comment by n1md4** [comment]
Setting the environment correctly works, thank you.

I usually use pip but there are problems with their platform at the moment status.python.org

**Comment by esheldon** [comment]
Great, I'm glad it worked for you.  I'm going to close.
