### ISSUE TITLE
Pip version of esutil has syntax error

### ISSUE THREAD

**Issue by jacobic** [esheldon/esutil#64]
Hi esheldon,

I just wanted to let you know that when installing with pip I find that is an error on import. It appears that there is an extra comma here which should be removed after the kwargs:

Traceback (most recent call last):
  File "src/models/make_models.py", line 11, in <module>
    from esutil.cosmology import Cosmo
  File "/u/jacobic/.local/anaconda3/envs/ezgal/lib/python2.7/site-packages/esutil/__init__.py", line 107, in <module>
    from . import integrate
  File "/u/jacobic/.local/anaconda3/envs/ezgal/lib/python2.7/site-packages/esutil/integrate/__init__.py", line 3, in <module>
    from . import util
  File "/u/jacobic/.local/anaconda3/envs/ezgal/lib/python2.7/site-packages/esutil/integrate/util.py", line 20, in <module>
    from .. import stat
  File "/u/jacobic/.local/anaconda3/envs/ezgal/lib/python2.7/site-packages/esutil/stat/__init__.py", line 11, in <module>
    from . import util
  File "/u/jacobic/.local/anaconda3/envs/ezgal/lib/python2.7/site-packages/esutil/stat/util.py", line 981
    sdev=False, **ignored_kw,
                            ^
SyntaxError: invalid syntax

After removing it manually it seems to work 

Cheers,
Jacob

**Comment by esheldon** [comment]
Thanks for the report.

python 2.7 doesn't allow the trailing comma (python3 does)

Do you want to make a pull request?
